### ISSUE TITLE
MACE Net ValueError: Ellipses lengths do not match.

### ISSUE THREAD

**Issue by yonatansverdlov** [chaitjo/geometric-gnn-dojo#10]
Hi!
When I run MACE net I get the following error: ValueError: Ellipses lengths do not match..
Would be happy for clarification.
Thanks!

**Comment by chaitjo** [comment]
Some more information would be needed in order for me to help. Which notebook did you face this issue in?

**Comment by yonatansverdlov** [comment]
The K-chain notebook.

**Comment by chaitjo** [comment]
Please try to re-install the conda environment from scratch and be very careful about how you install the correct library versions.

I tried a fresh installation from scratch following the README's instructions to set this up on my Macbook. Everything worked as expected.

Additionally, I tried to do an install with latest versions of the libraries (not those from the README). Everything still works as expected on my Macbook. Please try either the README instructions or the following:
```
conda create -n dojo python=3.10
conda activate dojo

pip install torch torchvision torchaudio

conda install matplotlib pandas networkx
conda install jupyterlab -c conda-forge
pip install e3nn==0.4.4 ipdb ase

pip install torch-geometric
pip install torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cpu.html
```

**Comment by yonatansverdlov** [comment]
See fot the attached image, after I install exactly like you said, without
any tiny changes.

‫בתאריך יום ב׳, 22 בינו׳ 2024 ב-20:21 מאת ‪Chaitanya Joshi‬‏ <‪
***@***.***‬‏>:‬

**Comment by chaitjo** [comment]
Did it work?

**Comment by yonatansverdlov** [comment]
No it crashed

‫בתאריך יום ג׳, 23 בינו׳ 2024 ב-14:00 מאת ‪Chaitanya Joshi‬‏ <‪
***@***.***‬‏>:‬

**Comment by chaitjo** [comment]
In that case, I'm really not sure how to help you. I very strongly suspect that there are issues with your python environment setup.

I have tested the installation freshly, and it is working on my end.
