### ISSUE TITLE
Why equivariant and not invariant GNN layers?

### ISSUE THREAD

**Issue by shenoynikhil** [chaitjo/geometric-gnn-dojo#2]
Thank you so much for the tutorial. As someone not a part of Cambridge, this tutorial is extremely useful to get started with this domain. 

I had a question regarding one of the statements in the notebook,
> why did we build permutation invariant GNN models composed of permutation equivariant GNN layers?
The answer is that permutation equivariant GNN layers enable the model to better leverage the relational structure of the underlying nodes, as well as construct more powerful node representations by stacking several layers of these permutation equivariant operations. (You can try running a DeepSets model for QM9 yourself and see the performance reduce.)

I was curious about why the relational structure is important because the ordering of the nodes does not signify any meaning right?  I might be mistaken. In any case, I would be glad if you could clarify this or direct me to any useful resource.

**Comment by chaitjo** [comment]
Thank you for your interest @shenoynikhil. The relational structures, i.e. the graph structure or which nodes are related to which others by edges, is the only extra piece of information that GNNs leverage over DeepSets.

A DeepSet will treat all the nodes as independent entities in a set.

A GNN will additionally learn to incorporate the fact that some nodes are related to each other via edges.

A Transformer will compute all pairwise interactions.

Fabian Fuchs has excellent research on this: https://fabianfuchsml.github.io/learningonsets/

Hope it helps!
