### ISSUE TITLE
Geometric GNNs 101

### ISSUE THREAD

**Issue by OnlyEpisode** [chaitjo/geometric-gnn-dojo#6]
Hello~ I'm a beginner for equivariant deep learning. Could you offer an answer for Geometric GNNs 101? Some blanks still seem a little hard. Thank you!

**Comment by chaitjo** [comment]
Hello @OnlyEpisode, thank you for your interest!

Just email me your solutions, I would be happy to provide feedback (without giving away answers)!

A few people already did this and it was hopefully useful to them.

**Comment by chaitjo** [comment]
Closing the issue now -- feel free to open new issues regarding any queries!
