### ISSUE TITLE
Kernel crash on remote server

### ISSUE THREAD

**Issue by madhavkrishnan94** [chaitjo/geometric-gnn-dojo#7]
Thanks for creating a wonderful notebook.

After installing and cloning the repo on a remote server (following your instructions), I tried running the notebook. But I find that the kernel crashes at the cell where I load the QM9 dataset.

Any idea why this may be the case? Perhaps because it's too huge for my server to handle or am I missing something else?

Regards,
Madhav

**Comment by chaitjo** [comment]
Hello @madhavkrishnan94, which notebook is that?

If it is the 101 notebook which uses QM9, you can just simply run it on Collab (what it was designed to be run on).

Other experimental notebooks should work if you followed the setup properly.

I don't think QM9 is too huge by any standards. It should work on laptops.

**Comment by madhavkrishnan94** [comment]
Thanks, Chaitanya.

Yes, I was referring to the 101 notebook.

I tried cloning and running on a remote server I have access to, mainly because Colab times me out after a while and the pytorch package installation cell takes ~42 mins to finish running on Colab.

Anyway, I shall take a closer look.

**Comment by chaitjo** [comment]
You will have to install the library versions stated in the 101 collab notebook in order to run that; it may be different package versions compared to the full dojo repository. 

Closing the issue, feel free to re-open or ask further queries as new issues.
