### ISSUE TITLE
RuntimeError: Not compiled with CUDA support in DimeNet.

### ISSUE THREAD

**Issue by yonatansverdlov** [chaitjo/geometric-gnn-dojo#9]
Hi!
When I run DimeNet, In k-chian experiments, I have the following error: RuntimeError: Not compiled with CUDA support.
Also, in line 79 you access to self.triplet, but there is no such variable.
I would like your support.
Thanks!

**Comment by chaitjo** [comment]
Are you following all the installation steps in the README and using the specified version of PyTorch and PyG? Also, what operating system are you working on and are you using a GPU?

**Comment by yonatansverdlov** [comment]
Yes, but in the terminal installing torch sprase and torch scatter. doesn't work.
I used exactly the same version of torch, PyG. And I work on linux.

**Comment by chaitjo** [comment]
In that case, I believe you should first ensure that all the PyG-related libraries are installed. Generally, following the official PyG website's installation steps should work: https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html

Just make sure you ensure that you download the appropriate PyG and PyTorch for the CUDA version you have installed. Also make sure that the PyG installation is for the correct PyTorch version.

I know it can be cumbersome to set up PyG properly at times :(

**Comment by yonatansverdlov** [comment]
I did all as you said.

‫בתאריך יום ד׳, 17 בינו׳ 2024 ב-6:50 מאת ‪Chaitanya Joshi‬‏ <‪
***@***.***‬‏>:‬

**Comment by chaitjo** [comment]
In that case, I’ll try to test the installation again and let you know. I
don’t see why the code would not work if the python environment is set up
correctly.

**Comment by chaitjo** [comment]
(See #10 for discussions on setting up the python environment. I suspect that these issues are due to improperly installing PyG)
